import { cn } from "@passlet/ui/lib/utils";
import QR from "qrcode";
import type { HTMLAttributes } from "react";

interface QRCodeProps extends HTMLAttributes<HTMLDivElement> {
	background: string;
	data: string;
	foreground: string;
	robustness?: "L" | "M" | "Q" | "H";
}

export const QRCode = async ({
	data,
	foreground,
	background,
	robustness = "M",
	className,
	...props
}: QRCodeProps) => {
	const svg = await QR.toString(data, {
		type: "svg",
		color: {
			dark: foreground,
			light: background,
		},
		width: 200,
		errorCorrectionLevel: robustness,
	});

	return (
		<div
			className={cn("size-full", "[&_svg]:size-full", className)}
			// biome-ignore lint/security/noDangerouslySetInnerHtml: SVG is generated by qrcode, not supplied as markup.
			dangerouslySetInnerHTML={{ __html: svg }}
			{...props}
		/>
	);
};
