/**
 * Allowed top-level keys from Google's Wallet Objects discovery document:
 * https://walletobjects.googleapis.com/$discovery/rest?version=v1
 * Reference: https://developers.google.com/wallet/reference/rest/v1/<resource>
 * Update from those sources and record the reference with schema changes.
 */

export type GoogleResource =
	| "loyaltyClass"
	| "loyaltyObject"
	| "offerClass"
	| "offerObject"
	| "eventTicketClass"
	| "eventTicketObject"
	| "flightClass"
	| "flightObject"
	| "giftCardClass"
	| "giftCardObject"
	| "genericClass"
	| "genericObject"
	| "transitClass"
	| "transitObject";

const RESOURCE_KEYS: Record<GoogleResource, readonly string[]> = {
	loyaltyClass: [
		"accountIdLabel",
		"accountNameLabel",
		"allowMultipleUsersPerObject",
		"appLinkData",
		"callbackOptions",
		"classTemplateInfo",
		"countryCode",
		"discoverableProgram",
		"enableSmartTap",
		"heroImage",
		"hexBackgroundColor",
		"homepageUri",
		"id",
		"imageModulesData",
		"infoModuleData",
		"issuerName",
		"kind",
		"linksModuleData",
		"localizedAccountIdLabel",
		"localizedAccountNameLabel",
		"localizedIssuerName",
		"localizedProgramName",
		"localizedRewardsTier",
		"localizedRewardsTierLabel",
		"localizedSecondaryRewardsTier",
		"localizedSecondaryRewardsTierLabel",
		"locations",
		"merchantLocations",
		"messages",
		"multipleDevicesAndHoldersAllowedStatus",
		"notifyPreference",
		"programLogo",
		"programName",
		"redemptionIssuers",
		"review",
		"reviewStatus",
		"rewardsTier",
		"rewardsTierLabel",
		"secondaryRewardsTier",
		"secondaryRewardsTierLabel",
		"securityAnimation",
		"textModulesData",
		"valueAddedModuleData",
		"version",
		"viewUnlockRequirement",
		"wideProgramLogo",
		"wordMark",
	],
	loyaltyObject: [
		"accountId",
		"accountName",
		"appLinkData",
		"barcode",
		"classId",
		"classReference",
		"disableExpirationNotification",
		"groupingInfo",
		"hasLinkedDevice",
		"hasUsers",
		"heroImage",
		"id",
		"imageModulesData",
		"infoModuleData",
		"kind",
		"linkedObjectIds",
		"linkedOfferIds",
		"linksModuleData",
		"locations",
		"loyaltyPoints",
		"merchantLocations",
		"messages",
		"notifyPreference",
		"passConstraints",
		"rotatingBarcode",
		"saveRestrictions",
		"secondaryLoyaltyPoints",
		"smartTapRedemptionValue",
		"state",
		"textModulesData",
		"validTimeInterval",
		"valueAddedModuleData",
		"version",
	],
	offerClass: [
		"allowMultipleUsersPerObject",
		"appLinkData",
		"callbackOptions",
		"classTemplateInfo",
		"countryCode",
		"details",
		"enableSmartTap",
		"finePrint",
		"helpUri",
		"heroImage",
		"hexBackgroundColor",
		"homepageUri",
		"id",
		"imageModulesData",
		"infoModuleData",
		"issuerName",
		"kind",
		"linksModuleData",
		"localizedDetails",
		"localizedFinePrint",
		"localizedIssuerName",
		"localizedProvider",
		"localizedShortTitle",
		"localizedTitle",
		"locations",
		"merchantLocations",
		"messages",
		"multipleDevicesAndHoldersAllowedStatus",
		"notifyPreference",
		"provider",
		"redemptionChannel",
		"redemptionIssuers",
		"review",
		"reviewStatus",
		"securityAnimation",
		"shortTitle",
		"textModulesData",
		"title",
		"titleImage",
		"valueAddedModuleData",
		"version",
		"viewUnlockRequirement",
		"wideTitleImage",
		"wordMark",
	],
	offerObject: [
		"appLinkData",
		"barcode",
		"classId",
		"classReference",
		"disableExpirationNotification",
		"groupingInfo",
		"hasLinkedDevice",
		"hasUsers",
		"heroImage",
		"id",
		"imageModulesData",
		"infoModuleData",
		"kind",
		"linkedObjectIds",
		"linksModuleData",
		"locations",
		"merchantLocations",
		"messages",
		"notifyPreference",
		"passConstraints",
		"rotatingBarcode",
		"saveRestrictions",
		"smartTapRedemptionValue",
		"state",
		"textModulesData",
		"validTimeInterval",
		"valueAddedModuleData",
		"version",
	],
	eventTicketClass: [
		"allowMultipleUsersPerObject",
		"appLinkData",
		"callbackOptions",
		"classTemplateInfo",
		"confirmationCodeLabel",
		"countryCode",
		"customConfirmationCodeLabel",
		"customGateLabel",
		"customRowLabel",
		"customSeatLabel",
		"customSectionLabel",
		"dateTime",
		"enableSmartTap",
		"eventId",
		"eventName",
		"finePrint",
		"gateLabel",
		"heroImage",
		"hexBackgroundColor",
		"homepageUri",
		"id",
		"imageModulesData",
		"infoModuleData",
		"issuerName",
		"kind",
		"linksModuleData",
		"localizedIssuerName",
		"locations",
		"logo",
		"merchantLocations",
		"messages",
		"multipleDevicesAndHoldersAllowedStatus",
		"notifyPreference",
		"redemptionIssuers",
		"review",
		"reviewStatus",
		"rowLabel",
		"seatLabel",
		"sectionLabel",
		"securityAnimation",
		"textModulesData",
		"valueAddedModuleData",
		"venue",
		"version",
		"viewUnlockRequirement",
		"wideLogo",
		"wordMark",
	],
	eventTicketObject: [
		"appLinkData",
		"barcode",
		"classId",
		"classReference",
		"disableExpirationNotification",
		"faceValue",
		"groupingInfo",
		"hasLinkedDevice",
		"hasUsers",
		"heroImage",
		"hexBackgroundColor",
		"id",
		"imageModulesData",
		"infoModuleData",
		"kind",
		"linkedObjectIds",
		"linkedOfferIds",
		"linksModuleData",
		"locations",
		"merchantLocations",
		"messages",
		"notifyPreference",
		"passConstraints",
		"reservationInfo",
		"rotatingBarcode",
		"saveRestrictions",
		"seatInfo",
		"smartTapRedemptionValue",
		"state",
		"textModulesData",
		"ticketHolderName",
		"ticketNumber",
		"ticketType",
		"validTimeInterval",
		"valueAddedModuleData",
		"version",
	],
	flightClass: [
		"allowMultipleUsersPerObject",
		"appLinkData",
		"boardingAndSeatingPolicy",
		"callbackOptions",
		"classTemplateInfo",
		"countryCode",
		"destination",
		"enableSmartTap",
		"flightHeader",
		"flightStatus",
		"heroImage",
		"hexBackgroundColor",
		"homepageUri",
		"id",
		"imageModulesData",
		"infoModuleData",
		"issuerName",
		"kind",
		"languageOverride",
		"linksModuleData",
		"localBoardingDateTime",
		"localEstimatedOrActualArrivalDateTime",
		"localEstimatedOrActualDepartureDateTime",
		"localGateClosingDateTime",
		"localScheduledArrivalDateTime",
		"localScheduledDepartureDateTime",
		"localizedIssuerName",
		"locations",
		"merchantLocations",
		"messages",
		"multipleDevicesAndHoldersAllowedStatus",
		"notifyPreference",
		"origin",
		"redemptionIssuers",
		"review",
		"reviewStatus",
		"securityAnimation",
		"textModulesData",
		"valueAddedModuleData",
		"version",
		"viewUnlockRequirement",
		"wordMark",
	],
	flightObject: [
		"appLinkData",
		"barcode",
		"boardingAndSeatingInfo",
		"classId",
		"classReference",
		"disableExpirationNotification",
		"groupingInfo",
		"hasLinkedDevice",
		"hasUsers",
		"heroImage",
		"hexBackgroundColor",
		"id",
		"imageModulesData",
		"infoModuleData",
		"kind",
		"linkedObjectIds",
		"linksModuleData",
		"locations",
		"merchantLocations",
		"messages",
		"notifyPreference",
		"passConstraints",
		"passengerName",
		"reservationInfo",
		"rotatingBarcode",
		"saveRestrictions",
		"securityProgramLogo",
		"smartTapRedemptionValue",
		"state",
		"textModulesData",
		"validTimeInterval",
		"valueAddedModuleData",
		"version",
	],
	giftCardClass: [
		"allowBarcodeRedemption",
		"allowMultipleUsersPerObject",
		"appLinkData",
		"callbackOptions",
		"cardNumberLabel",
		"classTemplateInfo",
		"countryCode",
		"enableSmartTap",
		"eventNumberLabel",
		"heroImage",
		"hexBackgroundColor",
		"homepageUri",
		"id",
		"imageModulesData",
		"infoModuleData",
		"issuerName",
		"kind",
		"linksModuleData",
		"localizedCardNumberLabel",
		"localizedEventNumberLabel",
		"localizedIssuerName",
		"localizedMerchantName",
		"localizedPinLabel",
		"locations",
		"merchantLocations",
		"merchantName",
		"messages",
		"multipleDevicesAndHoldersAllowedStatus",
		"notifyPreference",
		"pinLabel",
		"programLogo",
		"redemptionIssuers",
		"review",
		"reviewStatus",
		"securityAnimation",
		"textModulesData",
		"valueAddedModuleData",
		"version",
		"viewUnlockRequirement",
		"wideProgramLogo",
		"wordMark",
	],
	giftCardObject: [
		"appLinkData",
		"balance",
		"balanceUpdateTime",
		"barcode",
		"cardNumber",
		"classId",
		"classReference",
		"disableExpirationNotification",
		"eventNumber",
		"groupingInfo",
		"hasLinkedDevice",
		"hasUsers",
		"heroImage",
		"id",
		"imageModulesData",
		"infoModuleData",
		"kind",
		"linkedObjectIds",
		"linksModuleData",
		"locations",
		"merchantLocations",
		"messages",
		"notifyPreference",
		"passConstraints",
		"pin",
		"rotatingBarcode",
		"saveRestrictions",
		"smartTapRedemptionValue",
		"state",
		"textModulesData",
		"validTimeInterval",
		"valueAddedModuleData",
		"version",
	],
	genericClass: [
		"appLinkData",
		"callbackOptions",
		"classTemplateInfo",
		"enableSmartTap",
		"id",
		"imageModulesData",
		"linksModuleData",
		"merchantLocations",
		"messages",
		"multipleDevicesAndHoldersAllowedStatus",
		"redemptionIssuers",
		"securityAnimation",
		"textModulesData",
		"valueAddedModuleData",
		"viewUnlockRequirement",
	],
	genericObject: [
		"appLinkData",
		"barcode",
		"cardTitle",
		"classId",
		"genericType",
		"groupingInfo",
		"hasUsers",
		"header",
		"heroImage",
		"hexBackgroundColor",
		"id",
		"imageModulesData",
		"linkedObjectIds",
		"linksModuleData",
		"logo",
		"merchantLocations",
		"messages",
		"notifications",
		"passConstraints",
		"rotatingBarcode",
		"saveRestrictions",
		"smartTapRedemptionValue",
		"state",
		"subheader",
		"textModulesData",
		"validTimeInterval",
		"valueAddedModuleData",
		"wideLogo",
	],
	transitClass: [
		"activationOptions",
		"allowMultipleUsersPerObject",
		"appLinkData",
		"callbackOptions",
		"classTemplateInfo",
		"countryCode",
		"customCarriageLabel",
		"customCoachLabel",
		"customConcessionCategoryLabel",
		"customConfirmationCodeLabel",
		"customDiscountMessageLabel",
		"customFareClassLabel",
		"customFareNameLabel",
		"customOtherRestrictionsLabel",
		"customPlatformLabel",
		"customPurchaseFaceValueLabel",
		"customPurchasePriceLabel",
		"customPurchaseReceiptNumberLabel",
		"customRouteRestrictionsDetailsLabel",
		"customRouteRestrictionsLabel",
		"customSeatLabel",
		"customTicketNumberLabel",
		"customTimeRestrictionsLabel",
		"customTransitTerminusNameLabel",
		"customZoneLabel",
		"enableSingleLegItinerary",
		"enableSmartTap",
		"heroImage",
		"hexBackgroundColor",
		"homepageUri",
		"id",
		"imageModulesData",
		"infoModuleData",
		"issuerName",
		"languageOverride",
		"linksModuleData",
		"localizedIssuerName",
		"locations",
		"logo",
		"merchantLocations",
		"messages",
		"multipleDevicesAndHoldersAllowedStatus",
		"notifyPreference",
		"redemptionIssuers",
		"review",
		"reviewStatus",
		"securityAnimation",
		"textModulesData",
		"transitOperatorName",
		"transitType",
		"valueAddedModuleData",
		"version",
		"viewUnlockRequirement",
		"watermark",
		"wideLogo",
		"wordMark",
	],
	transitObject: [
		"activationStatus",
		"appLinkData",
		"barcode",
		"classId",
		"classReference",
		"concessionCategory",
		"customConcessionCategory",
		"customTicketStatus",
		"deviceContext",
		"disableExpirationNotification",
		"groupingInfo",
		"hasLinkedDevice",
		"hasUsers",
		"heroImage",
		"hexBackgroundColor",
		"id",
		"imageModulesData",
		"infoModuleData",
		"linkedObjectIds",
		"linksModuleData",
		"locations",
		"merchantLocations",
		"messages",
		"notifyPreference",
		"passConstraints",
		"passengerNames",
		"passengerType",
		"purchaseDetails",
		"rotatingBarcode",
		"saveRestrictions",
		"smartTapRedemptionValue",
		"state",
		"textModulesData",
		"ticketLeg",
		"ticketLegs",
		"ticketNumber",
		"ticketRestrictions",
		"ticketStatus",
		"tripId",
		"tripType",
		"validTimeInterval",
		"valueAddedModuleData",
		"version",
	],
};

const DOC_BASE = "https://developers.google.com/wallet/reference/rest/v1";

function docUrl(resource: GoogleResource): string {
	return `${DOC_BASE}/${resource.toLowerCase()}`;
}

export function assertGoogleSchema(
	resource: GoogleResource,
	body: Record<string, unknown>
): void {
	const allowed = RESOURCE_KEYS[resource];
	// JSON.stringify omits undefined placeholders before requests reach Google.
	const unknown = Object.keys(body)
		.filter((key) => body[key] !== undefined && !allowed.includes(key))
		.sort();
	if (unknown.length > 0) {
		throw new Error(
			`${resource} carries unsupported key(s): ${unknown
				.map((key) => `"${key}"`)
				.join(", ")}.\nSee ${docUrl(resource)}`
		);
	}
}

export function assertRequiredKeys(
	resource: GoogleResource,
	body: Record<string, unknown>,
	required: readonly string[]
): void {
	const missing = required.filter((key) => body[key] === undefined);
	if (missing.length > 0) {
		throw new Error(
			`${resource} is missing required key(s): ${missing
				.map((key) => `"${key}"`)
				.join(", ")}.\nSee ${docUrl(resource)}`
		);
	}
}
