"use server";

import { headers } from "next/headers";
import { field, Wallet } from "passlet";
import {
	COLORS,
	type ColorValue,
	PATTERNS,
	type PatternType,
} from "@/lib/data";
import type { StripImages } from "@/lib/patterns";
import { checkRateLimit, recordPassCreated } from "@/lib/rate-limit";
import { SITE_MANIFEST } from "@/lib/site";
import type { WalletProvider } from "@/types/pass";
import { version } from "../../../../packages/passlet/package.json";

function requiredEnv(name: string): string {
	const value = process.env[name];
	if (!value) {
		throw new Error(`Missing environment variable: ${name}`);
	}
	return value;
}

interface CreatePassInput {
	banner?: StripImages;
	color: string;
	colorValue: ColorValue;
	/** When the pass was made, already formatted in the visitor's locale. */
	created: string;
	memberName: string;
	memberNo: string;
	pattern: PatternType;
	provider: WalletProvider;
	since: string;
	textColor: string;
}

interface CreatePassResult {
	appleBytes?: number[];
	googleJwt?: string;
	warnings: string[];
}

const APPLE_ICON_BASE64 =
	"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO7nWJ0AAAAASUVORK5CYII=";

// Read credentials per action; a module-scope failure would break every bundled action.
function appleCredentials() {
	return {
		passTypeIdentifier: requiredEnv("APPLE_PASS_TYPE_IDENTIFIER"),
		teamId: requiredEnv("APPLE_TEAM_ID"),
		signerCert: requiredEnv("APPLE_SIGNER_CERT"),
		signerKey: requiredEnv("APPLE_SIGNER_KEY"),
		wwdr: requiredEnv("APPLE_WWDR"),
	};
}

function googleCredentials() {
	return {
		issuerId: requiredEnv("GOOGLE_ISSUER_ID"),
		clientEmail: requiredEnv("GOOGLE_CLIENT_EMAIL"),
		privateKey: requiredEnv("GOOGLE_PRIVATE_KEY"),
	};
}

export async function createPassAction(
	input: CreatePassInput
): Promise<CreatePassResult> {
	// Throttle by client IP so the public playground can't be scripted to spam
	// Apple signing (CPU) or the Google Wallet API (writes to the real issuer).
	const headerList = await headers();
	const ip =
		headerList.get("x-forwarded-for")?.split(",")[0]?.trim() || "anonymous";
	const allowed = await checkRateLimit(ip);
	if (!allowed) {
		throw new Error(
			"You're creating passes too quickly. Please wait a minute and try again."
		);
	}

	const wallet = new Wallet(
		input.provider === "apple"
			? { apple: appleCredentials() }
			: { google: googleCredentials() }
	);

	const color = COLORS.find((c) => c.value === input.colorValue);
	const pattern = PATTERNS.find((p) => p.value === input.pattern);
	if (!(color && pattern)) {
		throw new Error("Unknown colour or pattern.");
	}
	const google = input.provider === "google";
	// Google fetches the hero image itself, so it has to be a public URL on
	// whichever deployment made the pass.
	const origin = `${headerList.get("x-forwarded-proto") ?? "https"}://${headerList.get("x-forwarded-host") ?? headerList.get("host")}`;

	const pass = wallet.loyalty({
		id: `passlet-${input.memberNo}`,
		// Google shows issuerName beside the logo and name as the big title, so
		// "Passlet" twice there; Apple uses name as the organisation name.
		name: google ? "Member card" : "Passlet",
		color: input.color,
		fields: [
			field.header("memberId", "ID"),
			field.secondary("member", "Member"),
			field.secondary("since", "Since"),
			// Back of the pass: Apple's (i) details screen, Google's text modules.
			// Apple turns attributedValue into links; Google gets google.links.
			field.back("design", "Your design"),
			field.back("created", "Created"),
			field.back("about", "About passlet", {
				value: "One API for Apple Wallet and Google Wallet passes.",
				attributedValue: `One API for Apple Wallet and Google Wallet passes.\n<a href="${SITE_MANIFEST.url}">Website</a> · <a href="${SITE_MANIFEST.github}">GitHub</a> · <a href="https://www.npmjs.com/package/passlet">npm</a>`,
			}),
			field.back(
				"terms",
				"Terms",
				"This is a demo pass. It opens no doors, earns no points and never expires. It just looks good in your Wallet."
			),
			field.back("builtBy", "Made by", {
				value: "Oscar Treviño",
				attributedValue: '<a href="https://oscartrevio.xyz">Oscar Treviño</a>',
			}),
			field.back("serial", "Serial number"),
			field.back(
				"generator",
				"Generated by",
				`passlet v${version} · a loyalty pass (storeCard on Apple, loyaltyObject on Google)`
			),
		],
		apple: {
			logoText: "Passlet",
			icon: Buffer.from(APPLE_ICON_BASE64, "base64"),
			strip: input.banner && {
				base: Buffer.from(input.banner.base, "base64"),
				retina: Buffer.from(input.banner.retina, "base64"),
				superRetina: Buffer.from(input.banner.superRetina, "base64"),
			},
			foregroundColor: input.textColor,
			labelColor: input.textColor,
		},
		google: {
			logo: process.env.GOOGLE_LOGO_URL,
			issuerName: "Passlet",
			hero: `${origin}/hero/${color.value}/${pattern.value}`,
			links: [
				{ uri: SITE_MANIFEST.url, description: "Website" },
				{ uri: SITE_MANIFEST.github, description: "GitHub" },
				{ uri: "https://www.npmjs.com/package/passlet", description: "npm" },
				{ uri: "https://oscartrevio.xyz", description: "Oscar Treviño" },
			],
		},
	});

	// The prefix keeps these objects apart from anything else on the same
	// Google issuer; the pass itself only shows the number.
	const serial = String(Date.now());
	const serialNumber = `passlet-${serial}`;
	const issued = await pass.create({
		serialNumber,
		values: {
			memberId: input.memberNo,
			member: input.memberName,
			since: input.since,
			design: `${color.label} · ${pattern.label}`,
			created: input.created,
			serial,
		},
		barcode: {
			format: "QR",
			value: "https://github.com/oscartrevio/passlet",
			// Google's default card has no free text slot except under the QR.
			altText: google ? `Member since ${input.since}` : "",
		},
	});

	await recordPassCreated(input.memberName, input.provider);

	return {
		appleBytes:
			input.provider === "apple" && issued.apple
				? Array.from(issued.apple)
				: undefined,
		googleJwt:
			input.provider === "google" ? (issued.google ?? undefined) : undefined,
		warnings: issued.warnings,
	};
}
